trigger:
  - master

jobs:

  - job: conan
    timeoutInMinutes: 20

    pool:
      vmImage: 'vs2017-win2016'

    steps:

      - task: Bash@3
        inputs:
          script: |
            pip install conan --upgrade
            conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"
            conan create . FMI4cpp/testing
          workingDirectory: '$(system.defaultWorkingDirectory)'
          targetType: inline

      - task: Bash@3
        inputs:
          script: conan install . -s build_type=Debug --install-folder=build --build FMI4cpp
          workingDirectory: '$(system.defaultWorkingDirectory)/test_package'
          targetType: inline
      
      - task: CMake@1
        inputs:
          workingDirectory: '$(system.defaultWorkingDirectory)/test_package/build'
          cmakeArgs: '.. -A x64'

      - task: CMake@1
        inputs:
          workingDirectory: '$(system.defaultWorkingDirectory)/test_package/build'
          cmakeArgs: '--build .'

      - task: Bash@3
        inputs:
          script: 'ctest -C Debug'
          workingDirectory: '$(system.defaultWorkingDirectory)/test_package/build'
          targetType: inline
