version: 2
jobs:
  build:
    docker:
      - image: lasote/conangcc7
    steps:
      - checkout
      - run:
          name: Update conan
          command: 'sudo pip install conan --upgrade'

      - restore_cache:
          keys:
            - conan-cache-v1--{{ checksum "conanfile.py" }}
            - conan-cache-v1

      - run:
          name: Conan create
          command: 'conan create . markaren/testing'

      - save_cache:
          paths:
            - ~/.conan
          key: conan-cache-v1--{{ checksum "conanfile.py" }}

      - run:
          name: Conan install
          command: 'cd test_package && conan install . -s build_type=Debug -s compiler.libcxx=libstdc++11 --install-folder=build --build fmi4cpp'

      - run:
          name: Configuring
          command: 'cd test_package && cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug'

      - run:
          name: Building
          command: 'cd test_package && cmake --build build'

      - run:
          name: Test
          command: 'cd test_package/build && ctest'
